### ISSUE TITLE
Error when moving characters

### ISSUE THREAD

**Issue by hen** [zz1000zz/OCTGN_TF#25] opened 2020-03-12 00:54 UTC
Here's the error when you move a character. I get it when using Play Characters, and then subsequently moving them.

Hitting Play Characters for this:

https://github.com/hen/Decks/blob/master/Jank/OneShallSmash.o8d

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hen\AppData\Local\Programs\OCTGN\Data\GameDatabase\f44befce-4d6d-4fb9-a286-9585f36aece9\scripts\actions.py", line 504, in onCardsMoved
  File "<string>", line 297, in name
SystemError: Object reference not set to an instance of an object.

onCardsMoved(EventArgument({"player":Player(1), "cards":[Card(65606)], "fromGroups":[Pile(16842756, 'Characters', Player(1))], "toGroups":[table], "indexs":[0], "xs":[0], "ys":[0], "highlights":["None"], "markers":["{}"], "faceups":[True], "filters":["None"], "alternates":[""]}))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hen\AppData\Local\Programs\OCTGN\Data\GameDatabase\f44befce-4d6d-4fb9-a286-9585f36aece9\scripts\actions.py", line 504, in onCardsMoved
  File "<string>", line 297, in name
SystemError: Object reference not set to an instance of an object.

onCardsMoved(EventArgument({"player":Player(1), "cards":[Card(65607)], "fromGroups":[Pile(16842756, 'Characters', Player(1))], "toGroups":[table], "indexs":[0], "xs":[0], "ys":[0], "highlights":["None"], "markers":["{}"], "faceups":[True], "filters":["None"], "alternates":[""]}))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hen\AppData\Local\Programs\OCTGN\Data\GameDatabase\f44befce-4d6d-4fb9-a286-9585f36aece9\scripts\actions.py", line 504, in onCardsMoved
  File "<string>", line 297, in name
SystemError: Object reference not set to an instance of an object.

onCardsMoved(EventArgument({"player":Player(1), "cards":[Card(65608)], "fromGroups":[Pile(16842756, 'Characters', Player(1))], "toGroups":[table], "indexs":[0], "xs":[0], "ys":[0], "highlights":["None"], "markers":["{}"], "faceups":[True], "filters":["None"], "alternates":[""]}))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hen\AppData\Local\Programs\OCTGN\Data\GameDatabase\f44befce-4d6d-4fb9-a286-9585f36aece9\scripts\actions.py", line 504, in onCardsMoved
  File "<string>", line 297, in name
SystemError: Object reference not set to an instance of an object.

onCardsMoved(EventArgument({"player":Player(1), "cards":[Card(65608)], "fromGroups":[table], "toGroups":[table], "indexs":[2], "xs":[-315], "ys":[28], "highlights":["None"], "markers":["{}"], "faceups":[True], "filters":["None"], "alternates":[""]}))

**Comment by zz1000zz** [comment] 2020-03-13 03:14
Others have reported this same issue, though it's unclear if it is limited to card movement caused by the Play Characters command.  I've been unable to replicate it, with things working as intended whenever I test.

Even so, I'll be closing this.  I've wrapped the section of code that's the source of the error in a try/except block so if it fails, it will do so silently and without effect on the game.  The worst that should happen because of this is the Undo command will be rendered non-functional for people who would otherwise have gotten these errors.

That's obviously not desirable but the Undo feature is in active development.  If the change does make the Undo feature not work, we can start a new issue ticket and reference this one.

**Closed as completed by zz1000zz** 2020-03-13 03:14 UTC
